name: Test workflow
on:
  workflow_dispatch:
  push:

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54
        with:
          deno-version: v1.x

      - name: Run script
        env:
          DISCORD_TOKEN: ${{secrets.DISCORD_TOKEN}}
        run: deno run -A discordTest.ts
